name: healthcheck
on: 
  schedule:
    - cron: '0 * * * *'

jobs:
  healthCheck:
    runs-on: ubuntu-latest
    steps:
      - name: do health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://app-test-kirsty-alice.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s
  