name: healthcheck
on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  healthCheck:
    steps:
      - name: do health check
        runs-on: ubuntu-latest
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://app-test-kirsty-alice.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s
  